export { WorkbenchPageBuilder } from './src/main/ets/pages/WorkbenchPage';

export { CampusCardPageBuilder } from './src/main/ets/pages/fuwu/CampusCardPage';

export { CanteenPageBuilder } from './src/main/ets/pages/fuwu/CanteenPage';

export { ClinicPageBuilder } from './src/main/ets/pages/fuwu/ClinicPage';

export { ElectricityBillRechargePageBuilder } from './src/main/ets/pages/fuwu/ElectricityBillRechargePage';

export { GymPageBuilder } from './src/main/ets/pages/fuwu/GymPage';

export { LibraryPageBuilder } from './src/main/ets/pages/fuwu/LibraryPage';

export { LostAndFoundPageBuilder } from './src/main/ets/pages/fuwu/LostAndFoundPage';

export { ScholarshipPageBuilder } from './src/main/ets/pages/fuwu/bailian/ScholarshipPage';

export { TeachingBuildingPageBuilder } from './src/main/ets/pages/fuwu/TeachingBuildingPage';

