export enum AppStorageMap {
  USER_INFO = 'userInfo',
  TOKEN = 'token',
  PRIVACY_POLICY_KEY = 'privacyPolicyKey'
}

export enum RouterMap {
  // 入口页
  MAIN_PAGE = 'MainEntry',

  // 首页
  HOME_PAGE = 'HomePage',
  // 快捷功能详情页
  ALL_FUNCTIONS = 'AllFunctionsPage',
  // 校园通知详情页
  NOTIFICATION_LIST = 'NotificationListPage',
  // 校园动态详情页
  NEWS_LIST = 'NewsListPage',

  // ai对话页面
  AI_PAGE = 'AiPage',
  // 聊天页面
  CHAT_PAGE = 'ChatPage',
  // 会话详情页面
  SESSION_DETAIL_PAGE = 'SessionDetailPage',

  // 知识库页面
  KNOWLEDGE_PAGE = 'KnowledgePage',

  // 工作台页面
  WORKBENCH_PAGE = 'WorkbenchPage',
  // 奖助助手页面
  SCHOLARSHIP_PAGE = 'ScholarshipPage',
  // 食堂页面
  CANTEEN_PAGE = 'CanteenPage',
  // 图书馆页面
  LIBRARY_PAGE = 'LibraryPage',
  // 体育馆页面
  GYM_PAGE = 'GymPage',
  // 教学楼页面
  TEACHING_BUILDING_PAGE = 'TeachingBuildingPage',
  // 校园卡页面
  CAMPUS_CARD_PAGE = 'CampusCardPage',
  // 电费充值页面
  ELECTRICITY_BILL_RECHARGE_PAGE = 'ElectricityBillRechargePage',
  // 医务室页面
  CLINIC_PAGE = 'ClinicPage',
  // 失物招领页面
  LOST_AND_FOUND_PAGE = 'LostAndFoundPage',

  // 个人主页
  PROFILE_PAGE = 'ProfilePage',
  // 账号设置页面
  ACCOUNT_SETTINGS_PAGE = 'AccountSettingsPage',
  // 密码设置
  PASSWORD_SETTINGS_PAGE = 'PasswordSettingsPage',
  // 解绑手机
  UNBIND_PHONE_PAGE = 'UnbindPhonePage',
  // 通知设置页面
  NOTIFICATION_SETTINGS_PAGE = 'NotificationSettingsPage',
  // 通用设置页面
  GENERAL_SETTINGS_PAGE = 'GeneralSettingsPage',
  // 关于页面
  ABOUT_PAGE = 'AboutPage',
  // 编辑个人信息页面
  EDIT_PROFILE_PAGE = 'EditProfilePage',
  // 登录页面
  LOGIN_PAGE = 'LoginPage',
  COURSE_DETAIL_PAGE = 'CourseDetailPage',
  COURSE_PAGE = 'CoursePage'
}