export enum AppStorageMap {
  USER_INFO = 'userInfo',
  TOKEN = 'token',
  PRIVACY_POLICY_KEY = 'privacyPolicyKey'
}

export enum RouterMap {
  // 入口页
  MAIN_PAGE = 'MainEntry',
  // 首页
  HOME_PAGE = 'HomePage',
  // 快捷功能详情页
  ALL_FUNCTIONS = 'AllFunctionsPage',
  // 校园通知详情页
  NOTIFICATION_LIST = 'NotificationListPage',
  // 校园动态详情页
  NEWS_LIST = 'NewsListPage',
  // ai对话页面
  AI_PAGE = 'AiPage',
  // 知识库页面
  KNOWLEDGE_PAGE = 'KnowledgePage',
  // 工作台页面
  WORKBENCH_PAGE = 'WorkbenchPage',
  // 个人主页
  PROFILE_PAGE = 'ProfilePage',
  // 账号设置页面
  ACCOUNT_SETTINGS_PAGE = 'AccountSettingsPage',
  // 通知设置页面
  NOTIFICATION_SETTINGS_PAGE = 'NotificationSettingsPage',
  // 通用设置页面
  GENERAL_SETTINGS_PAGE = 'GeneralSettingsPage',
  // 关于页面
  ABOUT_PAGE = 'AboutPage',
  // 编辑个人信息页面
  EDIT_PROFILE_PAGE = 'EditProfilePage',
  // 登录页面
  LOGIN_PAGE = 'LoginPage',
  COURSE_DETAIL_PAGE = 'CourseDetailPage',
  COURSE_PAGE = 'CoursePage'
}